# Generated by Django 4.2.17 on 2025-01-24 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='date',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='time',
        ),
        migrations.AddField(
            model_name='booking',
            name='company',
            field=models.CharField(default='Unknown Company', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='duration',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(default='Unknown', max_length=15),
        ),
        migrations.AddField(
            model_name='booking',
            name='preferred_contact_time',
            field=models.CharField(blank=True, default='Anytime', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='preferred_contact_type',
            field=models.CharField(default='Email', max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='returning_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='service_type',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_time',
            field=models.CharField(default='00:00', max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='timeslot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='book.timeslot'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='day',
            field=models.DateField(unique=True),
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
