# Generated by Django 4.2.17 on 2025-01-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_rename_date_booking_start_date_remove_booking_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='day',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('day', 'slot_type')},
        ),
    ]
